//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEG.Website.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEG.Website.Resource.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT NEG.
        /// </summary>
        internal static string AboutNEG {
            get {
                return ResourceManager.GetString("AboutNEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                &lt;div&gt;
        ///                    &lt;div style=&quot;font-size: 18px;&quot; &gt;NEG is a javascript framework, which was developed by SHEC in 2012, for purpose of increasing our
        ///                    productivity at work of Web UI.&lt;/div&gt; 
        ///                    &lt;h3&gt;There are three advantage of NEG outlined below.&lt;/h3&gt; 
        ///	                &lt;ol class=&quot;none-list&quot;&gt;
        ///                        &lt;li&gt;1.  Easy-to-understand interface and modularization development &lt;/li&gt;
        ///		                    &lt;div class=&quot;b&quot;&gt;Any users of NEG, bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutNEGBody {
            get {
                return ResourceManager.GetString("AboutNEGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PART 2 - [NEG.JS] INTRODUCTORY.
        /// </summary>
        internal static string Introductory {
            get {
                return ResourceManager.GetString("Introductory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the most basic and useful feature is all of Javascript code run in a sandbox runtime..
        /// </summary>
        internal static string IntroductoryStep1 {
            get {
                return ResourceManager.GetString("IntroductoryStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NEG.JS] QUICK START.
        /// </summary>
        internal static string QuickStart {
            get {
                return ResourceManager.GetString("QuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s define a module by NEG.
        /// </summary>
        internal static string QuickStartStep1 {
            get {
                return ResourceManager.GetString("QuickStartStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, we can require module and use it..
        /// </summary>
        internal static string QuickStartStep2 {
            get {
                return ResourceManager.GetString("QuickStartStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PART 1 - GET SETUP.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;script src=&quot;js/{0}.js&quot;&amp;gt;&amp;lt;/script&amp;gt;.
        /// </summary>
        internal static string SetupScript {
            get {
                return ResourceManager.GetString("SetupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and unzip the NEG.JS from &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string SetupStep1 {
            get {
                return ResourceManager.GetString("SetupStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look inside the &lt;pre class=&quot;prettyprint inline&quot;&gt;release&lt;/pre &gt; folder to find &lt;pre class=&quot;prettyprint inline&quot;&gt;{0}.js&lt;/pre&gt; and add this to your page.
        /// </summary>
        internal static string SetupStep2 {
            get {
                return ResourceManager.GetString("SetupStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTORIAL.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
    }
}
