//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEG.Website.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEG.Website.Resource.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEG简介.
        /// </summary>
        internal static string AboutNEG {
            get {
                return ResourceManager.GetString("AboutNEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--&lt;h3&gt;WHY IS NEG ?&lt;/h3&gt; --&gt;
        ///                   &lt;h3&gt;为什么是 NEG ?&lt;/h3&gt; 
        ///                   &lt;p&gt;
        ///                        随着Newegg网站业务逐渐增加，前端交互日益复杂，旧版本的JS框架从性能，效果，业务上都满足不了开发需求；一个动态加载，擅长模块化的Javascript框架 NEG 可以很好地解决这个问题。
        ///                    &lt;/p&gt;
        ///
        ///                    &lt;br/&gt;
        ///
        ///                    &lt;h3&gt;不是有jQuery了吗 ?&lt;/h3&gt; 
        ///                    &lt;p&gt;
        ///                        jQuery 是一个功能非常强大的工具类，但不能很好地解决动态加载，模块化的问题（如header里引入很多JS 文件），而NEG也和jQuery 很好地兼容，你可以在NEG里将jQuery作为一个模块来使用。
        ///                    &lt;/p&gt;
        ///&lt;br/&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutNEGBody {
            get {
                return ResourceManager.GetString("AboutNEGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 举例.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NEG.JS] 简介.
        /// </summary>
        internal static string Introductory {
            get {
                return ResourceManager.GetString("Introductory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEG最重要的一个特质：代码在沙箱里执行。.
        /// </summary>
        internal static string IntroductoryStep1 {
            get {
                return ResourceManager.GetString("IntroductoryStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首先，来定义一个Module.
        /// </summary>
        internal static string QuickStartStep1 {
            get {
                return ResourceManager.GetString("QuickStartStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 然后，在NEG沙箱里Require回来，并使用.
        /// </summary>
        internal static string QuickStartStep2 {
            get {
                return ResourceManager.GetString("QuickStartStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回值.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;下载&lt;/a&gt;并解压缩 NEG.JS .
        /// </summary>
        internal static string SetupStep1 {
            get {
                return ResourceManager.GetString("SetupStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将 &lt;pre class=&quot;prettyprint inline&quot;&gt;release&lt;/pre &gt; 目录拷贝到网站目录JS下，找到 &lt;pre class=&quot;prettyprint inline&quot;&gt;{0}.js&lt;/pre&gt;，然后引入到页面.
        /// </summary>
        internal static string SetupStep2 {
            get {
                return ResourceManager.GetString("SetupStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简介.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语法.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教程.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
    }
}
